from .tables.base import CRUDMixin
from .tables.dance_style import DanceStyle
from .tables.hall import Hall
from .tables.lesson import Lesson
from .tables.place import Place
from .tables.price import Price
from .tables.subscription_request import SubscriptionRequest
from .tables.teacher import Teacher
from .tables.timeslot import Timeslot
from .tables.user import User